1. IMPORTATION DES PACKAGES


In [383]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sms
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


2. CHARGEMENT DES DONNEES

In [384]:
data=pd.read_csv("USA_Housing.csv")

In [385]:
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

3. EXPLORATION DES DONNEES

In [386]:
data.shape

(5000, 7)

In [387]:
data.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [388]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object 
dtypes: float64(6), object(1)
memory usage: 273.6+ KB


In [389]:
data.isnull().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [390]:
data.drop(['Address'], axis=1, inplace= True)

In [391]:
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09     23086.800503  1.059034e+06  
1                          3.09     40173.072174  1.505891e+06  
2                          5.13     36882.159400  1.058988e+06  
3                          3.26     34310.242831  1.260617e+06  
4                          4.23     26354.109472  6.309435e+05

DIVISION DES DONNES EN VARIABLE DEP ET INDEP

In [392]:
#variable independante
X = data.iloc[:, :-1].values

#Variable dependante
y = data.iloc[:, -1].values

In [393]:
X

array([[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,
        2.30868005e+04],
       [7.92486425e+04, 6.00289981e+00, 6.73082102e+00, 3.09000000e+00,
        4.01730722e+04],
       [6.12870672e+04, 5.86588984e+00, 8.51272743e+00, 5.13000000e+00,
        3.68821594e+04],
       ...,
       [6.33906869e+04, 7.25059061e+00, 4.80508098e+00, 2.13000000e+00,
        3.32661455e+04],
       [6.80013312e+04, 5.53438842e+00, 7.13014386e+00, 5.44000000e+00,
        4.26256202e+04],
       [6.55105818e+04, 5.99230531e+00, 6.79233610e+00, 4.07000000e+00,
        4.65012838e+04]])

In [394]:
y

array([1059033.55787012, 1505890.91484695, 1058987.98787608, ...,
       1030729.58315229, 1198656.87240769, 1298950.48026696])

SEPARATION DES DONNEES

In [395]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=30)

In [396]:
#affichage des dimentions
print("X train:", X_train.shape)
print("y train:", y_train.shape)

X train: (3500, 5)
y train: (3500,)


In [397]:
print("X test:", X_test.shape)
print("y test:", y_test.shape)

X test: (1500, 5)
y test: (1500,)


5.CRÉATION DU MODÈLE5.CREATION DU MODELE

5.1. REGRESSION LINEAIRE multiple 

In [398]:
#Création du model
model_lineaire = LinearRegression()

In [399]:
# Entrainement du modele
model_lineaire.fit(X_train, y_train)

LinearRegression()

In [400]:
#Faire la prédiction
y_test

array([1518387.14164684, 1375057.08346865, 1019127.7329514 , ...,
       1665515.24612232,  823941.92205867, 1132983.95515514])

In [401]:
y_predicted_lr = model_lineaire.predict(X_test)
y_predicted_lr

array([1466037.18162799, 1467071.86181542, 1101596.16978091, ...,
       1520358.20587819,  935336.04368947, 1338120.16213876])

In [402]:
mean_squared_error(y_test, y_predicted_lr)

10438016716.572054

In [403]:
r2_score(y_test, y_predicted_lr)

0.9125718521857675

In [404]:
print("Mean Squared Error:", mean_squared_error(y_test, y_predicted_lr))
print("R2 Squared:", r2_score(y_test, y_predicted_lr))

Mean Squared Error: 10438016716.572054
R2 Squared: 0.9125718521857675


In [405]:
data.shape

(5000, 6)

Verification de la prediction 

ATTACHAGE DES PARAMETRE D'EQUATION

In [406]:
model_lineaire.coef_


array([2.15305036e+01, 1.66477194e+05, 1.18820151e+05, 2.59721581e+03,
       1.54068095e+01])

In [407]:
model_lineaire.intercept_

-2636530.703463771

In [408]:
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09     23086.800503  1.059034e+06  
1                          3.09     40173.072174  1.505891e+06  
2                          5.13     36882.159400  1.058988e+06  
3                          3.26     34310.242831  1.260617e+06  
4                          4.23     26354.109472  6.309435e+05

RANDOM FORESTE

In [409]:
model_Random_Forest =RandomForestRegressor()
model_Random_Forest.fit(X_train, y_train)


RandomForestRegressor()

In [410]:
y_predicted_rf = model_Random_Forest.predict(X_test)

In [411]:
print("Mean Squared Error De Random Forest:", mean_squared_error(y_test, y_predicted_rf))
print("R2 Squared de Random Forest:", r2_score(y_test, y_predicted_rf))

Mean Squared Error De Random Forest: 14492420168.27277
R2 Squared de Random Forest: 0.878612433083569


DECISION TREE

In [412]:
model_decission_tree=DecisionTreeRegressor()
model_decission_tree.fit(X_train, y_train)

DecisionTreeRegressor()

y_predicted_dt = model_decission_tree.predict(X_test)

In [414]:
print("Mean Squar Error d arbre de decision:",mean_squared_error(y_test, y_predicted_dt)) 
print("r2_score d arbre de decision:", r2_score(y_test, y_predicted_dt))

Mean Squar Error d arbre de decision: 31392825884.071877
r2_score d arbre de decision: 0.7370557361398383
