IMPORTATION DES PACKAGES 

In [140]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sms
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


CHARGEMENT DES DONNÉES

In [141]:
data=pd.read_csv("Real-estate.csv")

In [142]:
data.head()

No  X1 date de transaction  X2 age de la maison  \
0   1                2012.917                 32.0   
1   2                2012.917                 19.5   
2   3                2013.583                 13.3   
3   4                2013.500                 13.3   
4   5                2012.833                  5.0   

   X3 distance jusqu'a la gare la plus proche  \
0                                    84.87882   
1                                   306.59470   
2                                   561.98450   
3                                   561.98450   
4                                   390.56840   

   X4 nombre de supermarket de proximite  X5 latitude  X6 longitude  \
0                                     10     24.98298     121.54024   
1                                      9     24.98034     121.53951   
2                                      5     24.98746     121.54391   
3                                      5     24.98746     121.54391   
4                                      5     24.97937     121.54245   

   Y prix de la maison par unite de surface  
0                                      37.9  
1                                      42.2  
2                                      47.3  
3                                      54.8  
4                                      43.1

EXPLORATION DES DONNEES

In [143]:
data.shape

(414, 8)

In [144]:
data.columns

Index(['No', 'X1 date de transaction', 'X2 age de la maison',
       'X3 distance jusqu'a la gare la plus proche',
       'X4 nombre de supermarket de proximite', 'X5 latitude', 'X6 longitude',
       'Y prix de la maison par unite de surface'],
      dtype='object')

In [145]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   No                                          414 non-null    int64  
 1   X1 date de transaction                      414 non-null    float64
 2   X2 age de la maison                         414 non-null    float64
 3   X3 distance jusqu'a la gare la plus proche  414 non-null    float64
 4   X4 nombre de supermarket de proximite       414 non-null    int64  
 5   X5 latitude                                 414 non-null    float64
 6   X6 longitude                                414 non-null    float64
 7   Y prix de la maison par unite de surface    414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB


In [146]:
#verifiction des valeur manquantes
data.isnull().sum()

No                                            0
X1 date de transaction                        0
X2 age de la maison                           0
X3 distance jusqu'a la gare la plus proche    0
X4 nombre de supermarket de proximite         0
X5 latitude                                   0
X6 longitude                                  0
Y prix de la maison par unite de surface      0
dtype: int64

In [147]:
data.head()

No  X1 date de transaction  X2 age de la maison  \
0   1                2012.917                 32.0   
1   2                2012.917                 19.5   
2   3                2013.583                 13.3   
3   4                2013.500                 13.3   
4   5                2012.833                  5.0   

   X3 distance jusqu'a la gare la plus proche  \
0                                    84.87882   
1                                   306.59470   
2                                   561.98450   
3                                   561.98450   
4                                   390.56840   

   X4 nombre de supermarket de proximite  X5 latitude  X6 longitude  \
0                                     10     24.98298     121.54024   
1                                      9     24.98034     121.53951   
2                                      5     24.98746     121.54391   
3                                      5     24.98746     121.54391   
4                                      5     24.97937     121.54245   

   Y prix de la maison par unite de surface  
0                                      37.9  
1                                      42.2  
2                                      47.3  
3                                      54.8  
4                                      43.1

DIVISION DES DONNES EN VARIABLE DEP ET INDEO

In [148]:
#variable independante
X = data.iloc[:, :-1].values

#Variable dependante
y = data.iloc[:, -1].values

In [149]:
X

array([[1.0000000e+00, 2.0129170e+03, 3.2000000e+01, ..., 1.0000000e+01,
        2.4982980e+01, 1.2154024e+02],
       [2.0000000e+00, 2.0129170e+03, 1.9500000e+01, ..., 9.0000000e+00,
        2.4980340e+01, 1.2153951e+02],
       [3.0000000e+00, 2.0135830e+03, 1.3300000e+01, ..., 5.0000000e+00,
        2.4987460e+01, 1.2154391e+02],
       ...,
       [4.1200000e+02, 2.0132500e+03, 1.8800000e+01, ..., 7.0000000e+00,
        2.4979230e+01, 1.2153986e+02],
       [4.1300000e+02, 2.0130000e+03, 8.1000000e+00, ..., 5.0000000e+00,
        2.4966740e+01, 1.2154067e+02],
       [4.1400000e+02, 2.0135000e+03, 6.5000000e+00, ..., 9.0000000e+00,
        2.4974330e+01, 1.2154310e+02]])

In [150]:
y

array([ 37.9,  42.2,  47.3,  54.8,  43.1,  32.1,  40.3,  46.7,  18.8,
        22.1,  41.4,  58.1,  39.3,  23.8,  34.3,  50.5,  70.1,  37.4,
        42.3,  47.7,  29.3,  51.6,  24.6,  47.9,  38.8,  27. ,  56.2,
        33.6,  47. ,  57.1,  22.1,  25. ,  34.2,  49.3,  55.1,  27.3,
        22.9,  25.3,  47.7,  46.2,  15.9,  18.2,  34.7,  34.1,  53.9,
        38.3,  42. ,  61.5,  13.4,  13.2,  44.2,  20.7,  27. ,  38.9,
        51.7,  13.7,  41.9,  53.5,  22.6,  42.4,  21.3,  63.2,  27.7,
        55. ,  25.3,  44.3,  50.7,  56.8,  36.2,  42. ,  59. ,  40.8,
        36.3,  20. ,  54.4,  29.5,  36.8,  25.6,  29.8,  26.5,  40.3,
        36.8,  48.1,  17.7,  43.7,  50.8,  27. ,  18.3,  48. ,  25.3,
        45.4,  43.2,  21.8,  16.1,  41. ,  51.8,  59.5,  34.6,  51. ,
        62.2,  38.2,  32.9,  54.4,  45.7,  30.5,  71. ,  47.1,  26.6,
        34.1,  28.4,  51.6,  39.4,  23.1,   7.6,  53.3,  46.4,  12.2,
        13. ,  30.6,  59.6,  31.3,  48. ,  32.5,  45.5,  57.4,  48.6,
        62.9,  55. ,

SEPARATION DES DONNEES

In [151]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20)

In [152]:
# Affcihage de dimensiom
print("X train:", X_train.shape)
print("y train:", y_train.shape)

X train: (289, 7)
y train: (289,)


In [153]:
print("X test:", X_test.shape)
print("y test:", y_test.shape)

X test: (125, 7)
y test: (125,)


CRÉATION DU MODÈLE

Regression multiple

In [154]:
#Création du model
model_lineaire = LinearRegression()

In [155]:
# Entrainement du modele
model_lineaire.fit(X_train, y_train)

LinearRegression()

In [156]:
#Faire la prédiction
y_test

array([40. , 45.2, 23.8, 48. , 41. , 41.1, 27.7, 23.1, 30.7, 39.6, 37. ,
       30.5, 55.9, 55.1, 41.4, 17.4, 41.9, 43.7, 50.2, 40.5, 18.8, 55. ,
       49.8, 30.8, 38.5, 19.2, 25.5, 42.2, 53.5, 37.4, 61.5, 43.9, 22.1,
       21.4, 63.3, 53.3, 46.7, 43.2, 33.1, 40.2, 54.4, 28.1, 42.1, 48.2,
       42.8, 45.1, 53. , 23.6, 42.6, 11.2, 29.5, 47.1, 38.4, 36.9, 49. ,
       51. , 37.2, 31.3, 36.5, 34.4, 56.3, 26.2, 21.8, 34.3, 46.4, 22.8,
       41. , 63.2, 35.6, 36.5, 50. , 51.8, 60.7, 45.4, 57.8, 24.7, 19. ,
       30.7, 30.6, 39. , 24.7, 42.5, 34.6, 23. , 53.7, 25.6, 36.8, 38.3,
       55.3, 47. , 41.5, 54.4, 51.6, 43.2, 52.5, 12.8, 40.1, 36.6, 25.3,
       51.7, 37.9, 51.6, 28.5, 27.3, 63.3, 52.2, 51.8, 44. , 31.3, 13. ,
       49.5, 22.1, 26.6, 29.3, 28.4, 36.7, 38.9, 18.3, 70.1, 17.7, 48.5,
       57.1, 27.7, 13.2, 36.3])

In [157]:
y_predicted_lr = model_lineaire.predict(X_test)
y_predicted_lr

array([44.30082882, 51.92008849, 27.44109342, 43.67836072, 43.71576816,
       35.99012993, 31.28833355, 31.04646482, 36.94181451, 32.73443448,
       30.26940906, 34.95568536, 51.62707834, 47.26449734, 33.73664044,
       12.44492231, 43.72794272, 44.16120234, 41.88804595, 48.77671546,
       16.58216538, 48.08694662, 54.67396943, 34.20742834, 39.35094933,
       13.043948  , 33.3145477 , 40.01066732, 48.84380243, 37.18272906,
       38.00553465, 39.03754703, 35.61528554, 37.22442216, 51.37581282,
       46.73309967, 47.42576646, 39.22919848, 41.89414517, 43.12141422,
       53.07980034, 31.69079419, 42.92023039, 46.54778533, 45.53542215,
       46.92306859, 46.80635776, 33.68184064, 39.2013181 , 12.0156867 ,
       29.70143553, 44.80196382, 42.25647165, 44.40066045, 47.79258434,
       47.42503651, 36.05411861, 30.17225635, 41.35318457, 42.64366931,
       50.39348314, 27.97183171, 28.59305207, 46.73854031, 38.62528662,
       26.97142055, 34.60252344, 50.73456414, 42.39436327, 35.60

In [158]:
#Evaluation du model
mean_squared_error(y_test, y_predicted_lr)

57.009687128079754

In [159]:
r2_score(y_test, y_predicted_lr)

0.649761834331565

In [160]:
print("Mean Squared Error:", mean_squared_error(y_test, y_predicted_lr))
print("R2 Squared:", r2_score(y_test, y_predicted_lr))

Mean Squared Error: 57.009687128079754
R2 Squared: 0.649761834331565


In [161]:
data.shape

(414, 8)

ATTACHAGE DES PARAMÈTRES D’EQUATION


In [162]:
model_lineaire.coef_

array([-2.94608929e-03,  5.75525152e+00, -2.70565854e-01, -4.17389100e-03,
        1.15718506e+00,  2.47639063e+02, -1.84731573e+01])

In [163]:
model_lineaire.intercept_

-15481.380267242565

In [164]:
data.head()

No  X1 date de transaction  X2 age de la maison  \
0   1                2012.917                 32.0   
1   2                2012.917                 19.5   
2   3                2013.583                 13.3   
3   4                2013.500                 13.3   
4   5                2012.833                  5.0   

   X3 distance jusqu'a la gare la plus proche  \
0                                    84.87882   
1                                   306.59470   
2                                   561.98450   
3                                   561.98450   
4                                   390.56840   

   X4 nombre de supermarket de proximite  X5 latitude  X6 longitude  \
0                                     10     24.98298     121.54024   
1                                      9     24.98034     121.53951   
2                                      5     24.98746     121.54391   
3                                      5     24.98746     121.54391   
4                                      5     24.97937     121.54245   

   Y prix de la maison par unite de surface  
0                                      37.9  
1                                      42.2  
2                                      47.3  
3                                      54.8  
4                                      43.1

RANDOM FOREST

In [165]:
model_Random_Forest =RandomForestRegressor()
model_Random_Forest.fit(X_train, y_train)

RandomForestRegressor()

In [166]:
y_predicted_rf = model_Random_Forest.predict(X_test)

In [167]:
print("Mean Squared Error De Random Forest:", mean_squared_error(y_test, y_predicted_rf))
print("R2 Squared de Random Forest:", r2_score(y_test, y_predicted_rf))

Mean Squared Error De Random Forest: 30.40613398400001
R2 Squared de Random Forest: 0.8132003677252327


FAIRE LA SIMPLE PRESICTION

ARBRE DE DÉCISION

In [168]:
model_decission_tree=DecisionTreeRegressor()
model_decission_tree.fit(X_train, y_train)

DecisionTreeRegressor()

In [169]:
y_predicted_dt = model_decission_tree.predict(X_test)

In [170]:
print("Mean Squar Error d arbre de decision:",mean_squared_error(y_test, y_predicted_dt)) 
print("r2_score d arbre de decision:", r2_score(y_test, y_predicted_dt))


Mean Squar Error d arbre de decision: 45.99727999999999
r2_score d arbre de decision: 0.717416393871025
